const mongoose = require("mongoose");
const ReissueRequest = require("../modules/servicing/reissue/schemas/ReissueRequest.schema");

function buildCleanupQuery() {
  return {
    status: "OFFLINE_REQUIRED",
    $and: [
      {
        $or: [
          { "creationSource.type": "AUTO_GENERATED" },
          { creationSource: { $exists: false } },
          { "creationSource.type": { $exists: false } },
        ],
      },
      { "pricingHistory.0": { $exists: false } },
      { "opsRemarks.0": { $exists: false } },
      { "auditLogs.0.metadata.selectedResultIndex": { $exists: false } },
      { $or: [{ newBookingId: null }, { newBookingId: { $exists: false } }] },
      { $or: [{ newPnr: null }, { newPnr: { $exists: false } }] },
      {
        $or: [
          { "billingReservation.reservationId": null },
          { "billingReservation.reservationId": { $exists: false } },
        ],
      },
    ],
  };
}

async function cleanupAutoGeneratedOfflineFallbacks({ apply = false } = {}) {
  const query = buildCleanupQuery();
  const candidates = await ReissueRequest.find(query)
    .select("_id reissueId bookingId status mode createdAt creationSource metadata")
    .lean();

  if (!apply) {
    return {
      dryRun: true,
      matchedCount: candidates.length,
      candidates,
    };
  }

  const ids = candidates.map((item) => item._id);
  if (!ids.length) {
    return {
      dryRun: false,
      deletedCount: 0,
      deletedIds: [],
    };
  }

  const result = await ReissueRequest.deleteMany({ _id: { $in: ids } });
  return {
    dryRun: false,
    deletedCount: result.deletedCount || 0,
    deletedIds: ids,
  };
}

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  const apply = process.argv.includes("--apply");
  const result = await cleanupAutoGeneratedOfflineFallbacks({ apply });
  console.log(JSON.stringify(result, null, 2));
  await mongoose.disconnect();
}

if (require.main === module) {
  run().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = {
  cleanupAutoGeneratedOfflineFallbacks,
  buildCleanupQuery,
};
