function toReissueDto(doc) {
  if (!doc) return null;
  const item = doc.toObject ? doc.toObject() : doc;

  return {
    id: item._id,
    reissueId: item.reissueId,
    bookingId: item.bookingId,
    originalBookingId: item.originalBookingId,
    originalPnr: item.originalPnr,
    newBookingId: item.newBookingId,
    newPnr: item.newPnr,
    userId: item.userId,
    corporateId: item.corporateId,
    companyId: item.companyId,
    supplier: item.supplier,
    airline: item.airline,
    provider: item.provider,
    mode: item.mode,
    status: item.status,
    reissueType: item.reissueType,
    supplierSupport: item.supplierSupport,
    oldJourney: item.oldJourney,
    newJourney: item.newJourney,
    fareDifference: item.fareDifference,
    reissueCharges: item.reissueCharges,
    totalAdjustment: item.totalAdjustment,
    billingMode: item.billingMode,
    billingReservation: item.billingReservation,
    walletAdjustment: item.walletAdjustment,
    creditAdjustment: item.creditAdjustment,
    opsRemarks: item.opsRemarks,
    uploadedTicket: item.uploadedTicket,
    uploadedInvoice: item.uploadedInvoice,
    revisedTicket: item.revisedTicket || item.uploadedTicket || null,
    revisedInvoice: item.revisedInvoice || item.uploadedInvoice || null,
    ticketData: item.ticketData || null,
    miniFareRules: item.miniFareRules,
    supplierResponse: item.supplierResponse,
    metadata: item.metadata,
    correlationId: item.correlationId,
    timeline: item.timeline,
    auditLogs: item.auditLogs,
    notificationLogs: item.notificationLogs,
    assignedOpsUserId: item.assignedOpsUserId,
    assignedAt: item.assignedAt,
    completedAt: item.completedAt,
    failedAt: item.failedAt,
    cancelledAt: item.cancelledAt,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
  };
}

module.exports = { toReissueDto };
